### PR TITLE
Fix #13 Use a responsive docs theme

### LINKED ISSUE #13: Use a responsive docs theme

### PR DESCRIPTION
**Pull request by pauloxnet**
In this PR I used the responsive theme [Furo](https://github.com/pradyunsg/furo) the same theme used by [urllib3](https://urllib3.readthedocs.io).

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Thank you, I'll take a look. I was using "better" but I think it's unmaintained now (https://github.com/irskep/sphinx-better-theme/issues/37)

**Comment by pauloxnet** [comment]
You're welcome.
I think Furo is one of the best responsive Sphinx theme and it's already used by widely used python libraries, like urlrlib3.

**Comment by dvarrazzo** [comment]
Thank you, it looks neat indeed.

I made a couple of customisations:

- I made the admonitions text not smaller: it doesn't make sense to say *warning* and then have an 80% font. https://pradyunsg.me/furo/reference/admonitions/
- "rubrics" are not styled. I added back a custom psycopg.css to handle them. I think it should be reported upstream. Rubric may be lousy as titles (I used them in the adaptation page and have to fix them) but they are useful e.g. to [group methods in a large class](https://www.psycopg.org/psycopg3/docs/connection.html#psycopg3.Connection.cursor)
- I see a bug:

```
$ ag --html furo.css docs/_build/html/
docs/_build/html/py-modindex.html
8:      <link rel="stylesheet" href="_static/styles/furo.css?state=215ef269dc62161487a00bb2">

docs/_build/html/search.html
6:    <meta name="generator" content="sphinx-3.3.0, furo 2020.11.19.beta18"/><title>Search - psycopg3 UNRELEASED documentation</title><link rel="stylesheet" href="_static/styles/furo.css?state=24409d7e53c40a70c60e5529">

docs/_build/html/install.html
8:      <link rel="stylesheet" href="_static/styles/furo.css?state=5e5b5a5c5ec24c0f6fdff3c5">

docs/_build/html/sql.html
8:      <link rel="stylesheet" href="_static/styles/furo.css?state=7692e6dfaafc5405ab0bcf05">

docs/_build/html/adaptation.html
8:      <link rel="stylesheet" href="_static/styles/furo.css?state=30c1434c4b4526705527e7ef">

docs/_build/html/index.html
8:      <link rel="stylesheet" href="_static/styles/furo.css?state=bcf6e916ed24f725ded6a4a2">
```

the asset hash changes so the same asset would be re-fetched every page.

**Comment by dvarrazzo** [comment]
Ah the rubic problem is reported: https://github.com/pradyunsg/furo/issues/33

**Comment by dvarrazzo** [comment]
Hashes problem reported at https://github.com/pradyunsg/furo/issues/38

**Comment by pauloxnet** [comment]
> Thank you, it looks neat indeed.

I'm happy you liked it. I think it's also actively maintained.

**Comment by pauloxnet** [comment]
It would be a great addition to use svg icons instead of png.

**Comment by dvarrazzo** [comment]
It's here if you want to re-render it at different size and with different background:

https://github.com/psycopg/psycopg-website/tree/master/assets/img/logo

**Comment by dvarrazzo** [comment]
Please note that the docs rendered on the website can diverge from what distributed in the sdist. The [Makefile](https://github.com/psycopg/psycopg-website/blob/master/Makefile) of the website has the possibility to add stuff to the template for instance (e.g. google analytics). Actually, thinking about it, maybe the funding banner would be better left out of the sources.

**Comment by dvarrazzo** [comment]
Using this theme will need some further changes to the doc, but I think it's better than the previous one, so I've merged this, we can work on cleanup in due time. Thank you very much for suggesting it, and if you would like to improve it further please feel free to suggest :)

**Comment by dvarrazzo** [comment]
Rendered docs are up:

https://www.psycopg.org/psycopg3/docs/

I need to reshuffle the structure altogether: there are several top-level title per page, and I think that confuses the theme in the choice of what to put on the left and on the right.

**Comment by pauloxnet** [comment]
I'm very happy that you found my PR an improvement for the project. The docs now looks better on mobile with dark theme.

**Pull request merged**
