### PR TITLE
add a tox environment to build the docs

### PR DESCRIPTION
**Pull request by dlax**
This adds a tox environment to build the docs.
Also included one change to make the docs build with python 3.7.

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Do built docs end up in the `docs/_build` dir in psycopg3 or do they stay in some `.tox` dir?

**Comment by dlax** [comment]
I put them in docs/_build as I noticed this was used for that already. 
But I can move them in .tox if you prefer.

**Comment by dlax** [comment]
Hm, perhaps it should rather go to _docs/build/html?

**Comment by dvarrazzo** [comment]
I think the best place is the one where they would go with a normal `make html`, so `docs/_build/html/`, so that then something down the pipeline knows where to find them instead of being inside a Tox hidden path. But as you are making this feature you probably have your use case in mind?

**Comment by dlax** [comment]
> I think the best place is the one where they would go with a normal `make html`, so `docs/_build/html/`, so that then something down the pipeline knows where to find them instead of being inside a Tox hidden path.

Done.

> But as you are making this feature you probably have your use case in mind?

At the moment, it's just to be able to build the docs in one command so 
I can certainly use 'make serve' for that.

In general, as a casual user, I am often happy to find a tox entry point 
to build the documentation locally without bothering with setting up the 
environment myself. Many projects have this.

The tox entry point might also be worth plugging into travis-ci.

**Comment by dvarrazzo** [comment]
> The tox entry point might also be worth plugging into travis-ci.

Yes, that was already up. It broke when I migrated from travis-ci.org to travis-ci.com. Maybe it's only an auth token problem though.

Anyway, happy to merge. Is the branch ready?

**Comment by dlax** [comment]
> Anyway, happy to merge. Is the branch ready?

Yes it is. Thanks!

**Pull request merged**
